from PyQt5.QtCore import QAbstractItemModel, QDate
from PyQt5.QtWidgets import QCompleter, QLineEdit


class DocumentView:
    """The view for the document generation window.

    This class wraps the UI object generated from the .ui file for the document
    window. It provides an API for the controller to interact with UI elements
    and to connect widget signals to controller methods.
    """

    def __init__(self, ui) -> None:
        """Initializes the DocumentView.

        Args:
            ui: The UI object (Ui_MainWindow) generated by pyuic.
        """
        self.ui = ui

    def get_save_folder_path(self) -> str:
        """Returns the path from the save folder path line edit."""
        return self.ui.save_file_path_line_lineEdit.text()

    def get_selected_document_type(self) -> str | None:
        """Returns the selected document type ('document' or 'bid')."""
        if self.ui.document_radioButton.isChecked():
            return "document"
        elif self.ui.bid_radioButton.isChecked():
            return "bid"
        return None

    def get_outgoing_number(self) -> str:
        """Returns the outgoing document number."""
        return self.ui.number_lineEdit.text()

    def get_date(self) -> QDate:
        """Returns the date from the date edit widget."""
        return self.ui.date_dateEdit.date()

    def get_whom_position(self) -> str:
        """Returns the 'recipient' position."""
        return self.ui.whom_position_lineEdit.text()

    def get_whom_fio(self) -> str:
        """Returns the 'recipient' full name."""
        return self.ui.whom_fio_lineEdit.text()

    def get_from_position(self) -> str:
        """Returns the 'sender' position."""
        return self.ui.from_position_lineEdit.text()

    def get_from_fio(self) -> str:
        """Returns the 'sender' full name."""
        return self.ui.from_fio_lineEdit.text()

    def set_product_nomenclature_lineedit(self, product_nomenclature: str) -> None:
        """Sets the text of the product nomenclature field."""
        self.ui.product_nomenclature_lineEdit.setText(product_nomenclature)

    def set_quantity_spinbox(self, quantity: int) -> None:
        """Sets the value of the product quantity spinbox."""
        self.ui.product_count_spinBox.setValue(quantity)

    def set_completer(
        self, line_edit: QLineEdit, model: QAbstractItemModel
    ) -> QCompleter:
        """Sets a QCompleter for a given line edit.

        Args:
            line_edit: The QLineEdit widget to attach the completer to.
            model: The data model for the completer.

        Returns:
            The created QCompleter instance.
        """
        completer = QCompleter(model, line_edit)
        completer.setCaseSensitivity(0)  # Case-insensitive
        completer.setCompletionMode(QCompleter.UnfilteredPopupCompletion)
        line_edit.setCompleter(completer)
        return completer

    def set_current_date(self, date: QDate) -> None:
        """Sets the date in the date edit widget."""
        self.ui.date_dateEdit.setDate(date)

    def set_save_folder_path(self, path: str) -> None:
        """Sets the path in the save folder path line edit."""
        self.ui.save_file_path_line_lineEdit.setText(path)

    def set_export_button_state(self, enabled: bool) -> None:
        """
        Sets the enabled state of the export button.
        
        Args:
            enabled (bool): True to enable the button, False to disable it.
        """
        self.ui.export_pushButton.setEnabled(enabled)

    def set_progress_bar_value(self, value: int) -> None:
        """Sets the value of the progress bar."""
        self.ui.progressBar.setValue(value)

    def set_progress_bar_labels_text(self, text: str, value: int) -> None:
        """Sets the text on the labels associated with the progress bar."""
        self.ui.progress_bar_labels_process_label.setText(text)
        self.ui.progress_bar_labels_percents_label.setText(f"{value}%")

    def choose_save_file_path_button_clicked(self, handler) -> None:
        """Connects a handler to the 'choose save path' button's clicked signal."""
        self.ui.save_file_path_line_choose_pushButton.clicked.connect(handler)

    def document_type_radiobutton_clicked(self, handler) -> None:
        """Connects a handler to the clicked signals of both document type radio buttons."""
        self.ui.document_radioButton.clicked.connect(handler)
        self.ui.bid_radioButton.clicked.connect(handler)

    def export_button_clicked(self, handler) -> None:
        """Connects a handler to the export button's clicked signal."""
        self.ui.export_pushButton.clicked.connect(handler)

    def outgoing_number_lineedit_text_changed(self, handler) -> None:
        """Connects a handler to the outgoing number field's textChanged signal."""
        self.ui.number_lineEdit.textChanged.connect(handler)

    def date_dateedit_changed(self, handler) -> None:
        """Connects a handler to the date edit's dateChanged signal."""
        self.ui.date_dateEdit.dateChanged.connect(handler)

    def from_position_lineedit_text_changed(self, handler) -> None:
        """Connects a handler to the 'from position' field's textChanged signal."""
        self.ui.from_position_lineEdit.textChanged.connect(handler)

    def from_fio_lineedit_text_changed(self, handler) -> None:
        """Connects a handler to the 'from FIO' field's textChanged signal."""
        self.ui.from_fio_lineEdit.textChanged.connect(handler)

    def whom_position_lineedit_text_changed(self, handler) -> None:
        """Connects a handler to the 'whom position' field's textChanged signal."""
        self.ui.whom_position_lineEdit.textChanged.connect(handler)

    def whom_fio_lineedit_text_changed(self, handler) -> None:
        """Connects a handler to the 'whom FIO' field's textChanged signal."""
        self.ui.whom_fio_lineEdit.textChanged.connect(handler)