from PyQt5.QtCore import QAbstractItemModel
from PyQt5.QtWidgets import QCompleter, QHeaderView, QLineEdit, QTableWidgetItem


class MainView:
    """The main view for the application.

    This class acts as a wrapper around the UI object generated from the .ui file.
    It provides a clean API for the controller to interact with the UI elements,
    such as getting/setting values and connecting signals to handlers.
    """

    def __init__(self, ui) -> None:
        """Initializes the MainView.

        Args:
            ui: The UI object (e.g., Ui_MainWindow) generated by pyuic.
        """
        self.ui = ui

        # Table setup
        headers = ["Номенклатура", "Количество", "Ед. изм."]
        self.ui.data_tableWidget.setColumnCount(len(headers))
        self.ui.data_tableWidget.setHorizontalHeaderLabels(headers)
        header = self.ui.data_tableWidget.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.Stretch)
        header.setSectionResizeMode(1, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QHeaderView.ResizeToContents)

    def get_search_field_text(self) -> str:
        """Returns the text from the search field."""
        return self.ui.search_line_lineEdit.text()

    def get_search_line_edit(self) -> QLineEdit:
        """Returns the QLineEdit widget used for searching."""
        return self.ui.search_line_lineEdit

    def set_search_completer(self, model: QAbstractItemModel) -> QCompleter:
        """Sets a QCompleter for the search field.

        Args:
            model: The data model for the completer.

        Returns:
            The created QCompleter instance.
        """
        completer = QCompleter(model, self.ui.search_line_lineEdit)
        completer.setCaseSensitivity(0)  # Case-insensitive
        completer.setCompletionMode(QCompleter.UnfilteredPopupCompletion)
        self.ui.search_line_lineEdit.setCompleter(completer)
        return completer

    def set_window_enabled_state(self, enabled: bool) -> None:
        """Sets the enabled state of the main window's central widget."""
        self.ui.centralwidget.setEnabled(enabled)

    def set_search_field_text(self, text: str) -> None:
        """Sets the text in the search field."""
        self.ui.search_line_lineEdit.setText(text)

    def set_search_in_materials_checkbox_text(self, text: str) -> None:
        """Sets the text of the 'search in materials' checkbox.

        Args:
            text: The product name to display, or an empty string to reset.
        """
        base_text = "Поиск по материалам изделия"
        checkbox_text = base_text if not text else f"{base_text}: {text}"
        self.ui.search_in_materials_checkBox.setText(checkbox_text)

    def update_clear_button_state(self, enabled: bool) -> None:
        """Updates the enabled state of the clear button."""
        self.ui.search_line_clear_pushButton.setEnabled(enabled)

    def update_table_widget_data(self, data: list[dict]) -> None:
        """Updates the data in the materials table.

        Args:
            data: A list of dictionaries, where each dictionary is a row.
        """
        self.ui.data_tableWidget.setRowCount(0)  # Clear only the rows

        # Populate the table with data
        for row_index, item in enumerate(data):
            self.ui.data_tableWidget.insertRow(row_index)

            # Column "Nomenclature"
            nomenclature_item = QTableWidgetItem(item.get("Номенклатура", ""))
            self.ui.data_tableWidget.setItem(row_index, 0, nomenclature_item)

            # Column "Quantity"
            quantity_item = QTableWidgetItem(str(item.get("Количество", "")))
            self.ui.data_tableWidget.setItem(row_index, 1, quantity_item)

            # Column "Unit"
            unit_item = QTableWidgetItem(item.get("Ед. изм.", ""))
            self.ui.data_tableWidget.setItem(row_index, 2, unit_item)

    def update_create_document_button_state(self, enabled: bool) -> None:
        """Updates the enabled state of the create document button."""
        self.ui.create_document_pushButton.setEnabled(enabled)

    def update_export_button_state(self, enabled: bool) -> None:
        """Updates the enabled state of the export button."""
        self.ui.export_pushButton.setEnabled(enabled)

    def clear_search_field(self) -> None:
        """Clears the text in the search field."""
        self.ui.search_line_lineEdit.clear()

    def search_field_changed(self, handler) -> None:
        """Connects a handler to the search field's textChanged signal.

        Args:
            handler: The function to call when the text changes.
        """
        self.ui.search_line_lineEdit.textChanged.connect(handler)

    def clear_button_clicked(self, handler) -> None:
        """Connects a handler to the clear button's clicked signal.

        Args:
            handler: The function to call when the button is clicked.
        """
        self.ui.search_line_clear_pushButton.clicked.connect(handler)

    def create_document_button_clicked(self, handler) -> None:
        """Connects a handler to the create document button's clicked signal.

        Args:
            handler: The function to call when the button is clicked.
        """
        self.ui.create_document_pushButton.clicked.connect(handler)

    def norms_calculations_changed(self, handler) -> None:
        """Connects a handler to the norms spinbox's valueChanged signal.

        Args:
            handler: The function to call when the value changes.
        """
        self.ui.norms_calculations_spinBox.valueChanged.connect(handler)

    def export_button_clicked(self, handler) -> None:
        """Connects a handler to the export button's clicked signal.

        Args:
            handler: The function to call when the button is clicked.
        """
        self.ui.export_pushButton.clicked.connect(handler)

    def search_in_materials_checkbox_state_changed(self, handler) -> None:
        """Connects a handler to the 'search in materials' checkbox's stateChanged signal.

        Args:
            handler: The function to call when the state changes. It will
                     receive a boolean (True for checked, False for unchecked).
        """
        # The lambda converts the Qt.CheckState enum (0 or 2) to a boolean.
        self.ui.search_in_materials_checkBox.stateChanged.connect(
            lambda state: handler(state == 2)
        )