# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/documentUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 615)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #F2F2F2;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #6B7280;\n"
"    color: #1F2937;\n"
"    font-weight: normal;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #8891A2;\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid #1F2937;\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #E9EFFB;\n"
"    color: #D3DEF5;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #CAD1E0;\n"
"    color: #1F2937;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 1px solid #F5F8FF;\n"
"    color: #D3DEF5;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #CAD1E0;\n"
"    padding: 4px 8px;\n"
"    color: #1F2937;\n"
"    selection-background-color: #2563EB;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QSpinBox:disabled {\n"
"    border: 1px solid #E9EFFB;\n"
"    background-color: #F8FAFC;\n"
"    color: #9CA3AF;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 1px solid #DBEAFE;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #10B981;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QProgressBar[error=\"true\"]::chunk {\n"
"    background-color: #EF4444;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #1F2937;\n"
"    spacing: 4px;\n"
"    border-radius: 6px; /* округленные углы */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.number_date_frame = QtWidgets.QFrame(self.centralwidget)
        self.number_date_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.number_date_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.number_date_frame.setObjectName("number_date_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.number_date_frame)
        self.horizontalLayout_3.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_3.setSpacing(16)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.number_frame = QtWidgets.QFrame(self.number_date_frame)
        self.number_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.number_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.number_frame.setObjectName("number_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.number_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.number_label = QtWidgets.QLabel(self.number_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_label.sizePolicy().hasHeightForWidth())
        self.number_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.number_label.setFont(font)
        self.number_label.setObjectName("number_label")
        self.horizontalLayout.addWidget(self.number_label)
        self.number_lineEdit = QtWidgets.QLineEdit(self.number_frame)
        self.number_lineEdit.setMinimumSize(QtCore.QSize(138, 0))
        self.number_lineEdit.setMaximumSize(QtCore.QSize(138, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number_lineEdit.setFont(font)
        self.number_lineEdit.setObjectName("number_lineEdit")
        self.horizontalLayout.addWidget(self.number_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.number_frame)
        self.date_frame = QtWidgets.QFrame(self.number_date_frame)
        self.date_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_frame.setObjectName("date_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.date_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(19)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date_label = QtWidgets.QLabel(self.date_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.horizontalLayout_2.addWidget(self.date_label)
        self.date_dateEdit = QtWidgets.QDateEdit(self.date_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_dateEdit.sizePolicy().hasHeightForWidth())
        self.date_dateEdit.setSizePolicy(sizePolicy)
        self.date_dateEdit.setMinimumSize(QtCore.QSize(138, 30))
        self.date_dateEdit.setMaximumSize(QtCore.QSize(138, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_dateEdit.setFont(font)
        self.date_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_dateEdit.setCalendarPopup(True)
        self.date_dateEdit.setObjectName("date_dateEdit")
        self.horizontalLayout_2.addWidget(self.date_dateEdit)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.date_frame)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_12.addWidget(self.number_date_frame)
        self.signatures_frame = QtWidgets.QFrame(self.centralwidget)
        self.signatures_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signatures_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signatures_frame.setObjectName("signatures_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.signatures_frame)
        self.horizontalLayout_8.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ku_signature_frame = QtWidgets.QFrame(self.signatures_frame)
        self.ku_signature_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ku_signature_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ku_signature_frame.setObjectName("ku_signature_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ku_signature_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ku_label = QtWidgets.QLabel(self.ku_signature_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ku_label.sizePolicy().hasHeightForWidth())
        self.ku_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.ku_label.setFont(font)
        self.ku_label.setObjectName("ku_label")
        self.verticalLayout_3.addWidget(self.ku_label)
        self.ku_actions_frame = QtWidgets.QFrame(self.ku_signature_frame)
        self.ku_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ku_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ku_actions_frame.setObjectName("ku_actions_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ku_actions_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ku_position_frame = QtWidgets.QFrame(self.ku_actions_frame)
        self.ku_position_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ku_position_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ku_position_frame.setObjectName("ku_position_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ku_position_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(33)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ku_position_label = QtWidgets.QLabel(self.ku_position_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.ku_position_label.setFont(font)
        self.ku_position_label.setObjectName("ku_position_label")
        self.horizontalLayout_4.addWidget(self.ku_position_label)
        self.ku_position_lineEdit = QtWidgets.QLineEdit(self.ku_position_frame)
        self.ku_position_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.ku_position_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ku_position_lineEdit.setFont(font)
        self.ku_position_lineEdit.setText("")
        self.ku_position_lineEdit.setObjectName("ku_position_lineEdit")
        self.horizontalLayout_4.addWidget(self.ku_position_lineEdit)
        self.verticalLayout_2.addWidget(self.ku_position_frame)
        self.ku_fio_frame = QtWidgets.QFrame(self.ku_actions_frame)
        self.ku_fio_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ku_fio_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ku_fio_frame.setObjectName("ku_fio_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ku_fio_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(19)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ku_fio_label = QtWidgets.QLabel(self.ku_fio_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.ku_fio_label.setFont(font)
        self.ku_fio_label.setObjectName("ku_fio_label")
        self.horizontalLayout_5.addWidget(self.ku_fio_label)
        self.ku_fio_lineEdit = QtWidgets.QLineEdit(self.ku_fio_frame)
        self.ku_fio_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.ku_fio_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ku_fio_lineEdit.setFont(font)
        self.ku_fio_lineEdit.setText("")
        self.ku_fio_lineEdit.setObjectName("ku_fio_lineEdit")
        self.horizontalLayout_5.addWidget(self.ku_fio_lineEdit)
        self.verticalLayout_2.addWidget(self.ku_fio_frame)
        self.verticalLayout_3.addWidget(self.ku_actions_frame)
        self.horizontalLayout_8.addWidget(self.ku_signature_frame)
        self.ceh_signature_frame = QtWidgets.QFrame(self.signatures_frame)
        self.ceh_signature_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ceh_signature_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ceh_signature_frame.setObjectName("ceh_signature_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ceh_signature_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ceh_label = QtWidgets.QLabel(self.ceh_signature_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ceh_label.sizePolicy().hasHeightForWidth())
        self.ceh_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.ceh_label.setFont(font)
        self.ceh_label.setObjectName("ceh_label")
        self.verticalLayout_4.addWidget(self.ceh_label)
        self.ceh_actions_frame = QtWidgets.QFrame(self.ceh_signature_frame)
        self.ceh_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ceh_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ceh_actions_frame.setObjectName("ceh_actions_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ceh_actions_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ceh_position_frame = QtWidgets.QFrame(self.ceh_actions_frame)
        self.ceh_position_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ceh_position_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ceh_position_frame.setObjectName("ceh_position_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.ceh_position_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(33)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ceh_position_label = QtWidgets.QLabel(self.ceh_position_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.ceh_position_label.setFont(font)
        self.ceh_position_label.setObjectName("ceh_position_label")
        self.horizontalLayout_6.addWidget(self.ceh_position_label)
        self.ceh_position_lineEdit = QtWidgets.QLineEdit(self.ceh_position_frame)
        self.ceh_position_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.ceh_position_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ceh_position_lineEdit.setFont(font)
        self.ceh_position_lineEdit.setText("")
        self.ceh_position_lineEdit.setObjectName("ceh_position_lineEdit")
        self.horizontalLayout_6.addWidget(self.ceh_position_lineEdit)
        self.verticalLayout_5.addWidget(self.ceh_position_frame)
        self.ceh_fio_frame = QtWidgets.QFrame(self.ceh_actions_frame)
        self.ceh_fio_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ceh_fio_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ceh_fio_frame.setObjectName("ceh_fio_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.ceh_fio_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(19)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ceh_fio_label = QtWidgets.QLabel(self.ceh_fio_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.ceh_fio_label.setFont(font)
        self.ceh_fio_label.setObjectName("ceh_fio_label")
        self.horizontalLayout_7.addWidget(self.ceh_fio_label)
        self.ceh_fio_lineEdit = QtWidgets.QLineEdit(self.ceh_fio_frame)
        self.ceh_fio_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.ceh_fio_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ceh_fio_lineEdit.setFont(font)
        self.ceh_fio_lineEdit.setText("")
        self.ceh_fio_lineEdit.setObjectName("ceh_fio_lineEdit")
        self.horizontalLayout_7.addWidget(self.ceh_fio_lineEdit)
        self.verticalLayout_5.addWidget(self.ceh_fio_frame)
        self.verticalLayout_4.addWidget(self.ceh_actions_frame)
        self.horizontalLayout_8.addWidget(self.ceh_signature_frame)
        self.verticalLayout_12.addWidget(self.signatures_frame)
        self.product_frame = QtWidgets.QFrame(self.centralwidget)
        self.product_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product_frame.setObjectName("product_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.product_frame)
        self.verticalLayout_7.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_7.setSpacing(16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.product_label = QtWidgets.QLabel(self.product_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.product_label.setFont(font)
        self.product_label.setObjectName("product_label")
        self.verticalLayout_7.addWidget(self.product_label)
        self.product_actions_frame = QtWidgets.QFrame(self.product_frame)
        self.product_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product_actions_frame.setObjectName("product_actions_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.product_actions_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.product_nomenclature_frame = QtWidgets.QFrame(self.product_actions_frame)
        self.product_nomenclature_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product_nomenclature_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product_nomenclature_frame.setObjectName("product_nomenclature_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.product_nomenclature_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(14)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.product_nomenclature_label = QtWidgets.QLabel(self.product_nomenclature_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_nomenclature_label.sizePolicy().hasHeightForWidth())
        self.product_nomenclature_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_nomenclature_label.setFont(font)
        self.product_nomenclature_label.setObjectName("product_nomenclature_label")
        self.horizontalLayout_9.addWidget(self.product_nomenclature_label)
        self.product_nomenclature_lineEdit = QtWidgets.QLineEdit(self.product_nomenclature_frame)
        self.product_nomenclature_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.product_nomenclature_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_nomenclature_lineEdit.setFont(font)
        self.product_nomenclature_lineEdit.setObjectName("product_nomenclature_lineEdit")
        self.horizontalLayout_9.addWidget(self.product_nomenclature_lineEdit)
        self.verticalLayout_6.addWidget(self.product_nomenclature_frame)
        self.product_count_frame = QtWidgets.QFrame(self.product_actions_frame)
        self.product_count_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product_count_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product_count_frame.setObjectName("product_count_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.product_count_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(30)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.product_count_label = QtWidgets.QLabel(self.product_count_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_count_label.sizePolicy().hasHeightForWidth())
        self.product_count_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_count_label.setFont(font)
        self.product_count_label.setObjectName("product_count_label")
        self.horizontalLayout_10.addWidget(self.product_count_label)
        self.product_count_spinBox = QtWidgets.QSpinBox(self.product_count_frame)
        self.product_count_spinBox.setMinimumSize(QtCore.QSize(138, 0))
        self.product_count_spinBox.setMaximumSize(QtCore.QSize(138, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_count_spinBox.setFont(font)
        self.product_count_spinBox.setMaximum(10000)
        self.product_count_spinBox.setObjectName("product_count_spinBox")
        self.horizontalLayout_10.addWidget(self.product_count_spinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout_6.addWidget(self.product_count_frame)
        self.verticalLayout_7.addWidget(self.product_actions_frame)
        self.verticalLayout_12.addWidget(self.product_frame)
        self.export_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_frame.sizePolicy().hasHeightForWidth())
        self.export_frame.setSizePolicy(sizePolicy)
        self.export_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_frame.setObjectName("export_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.export_frame)
        self.verticalLayout_8.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_8.setSpacing(16)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.choose_export_format_frame = QtWidgets.QFrame(self.export_frame)
        self.choose_export_format_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_export_format_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_export_format_frame.setObjectName("choose_export_format_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.choose_export_format_frame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.choose_export_format_label = QtWidgets.QLabel(self.choose_export_format_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_export_format_label.sizePolicy().hasHeightForWidth())
        self.choose_export_format_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_export_format_label.setFont(font)
        self.choose_export_format_label.setObjectName("choose_export_format_label")
        self.verticalLayout_9.addWidget(self.choose_export_format_label)
        self.export_formats_frame = QtWidgets.QFrame(self.choose_export_format_frame)
        self.export_formats_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_formats_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_formats_frame.setObjectName("export_formats_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.export_formats_frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(16)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.export_formats_excel_radioButton = QtWidgets.QRadioButton(self.export_formats_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export_formats_excel_radioButton.setFont(font)
        self.export_formats_excel_radioButton.setChecked(True)
        self.export_formats_excel_radioButton.setObjectName("export_formats_excel_radioButton")
        self.horizontalLayout_11.addWidget(self.export_formats_excel_radioButton)
        self.export_formats_word_radioButton = QtWidgets.QRadioButton(self.export_formats_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export_formats_word_radioButton.setFont(font)
        self.export_formats_word_radioButton.setObjectName("export_formats_word_radioButton")
        self.horizontalLayout_11.addWidget(self.export_formats_word_radioButton)
        self.export_formats_pdf_radioButton = QtWidgets.QRadioButton(self.export_formats_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export_formats_pdf_radioButton.setFont(font)
        self.export_formats_pdf_radioButton.setObjectName("export_formats_pdf_radioButton")
        self.horizontalLayout_11.addWidget(self.export_formats_pdf_radioButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.export_formats_frame)
        self.verticalLayout_8.addWidget(self.choose_export_format_frame)
        self.save_file_path_frame = QtWidgets.QFrame(self.export_frame)
        self.save_file_path_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_file_path_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_file_path_frame.setObjectName("save_file_path_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.save_file_path_frame)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.save_file_path_label = QtWidgets.QLabel(self.save_file_path_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_file_path_label.sizePolicy().hasHeightForWidth())
        self.save_file_path_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_file_path_label.setFont(font)
        self.save_file_path_label.setObjectName("save_file_path_label")
        self.verticalLayout_10.addWidget(self.save_file_path_label)
        self.save_file_path_line_frame = QtWidgets.QFrame(self.save_file_path_frame)
        self.save_file_path_line_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_file_path_line_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_file_path_line_frame.setObjectName("save_file_path_line_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.save_file_path_line_frame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.save_file_path_line_lineEdit = QtWidgets.QLineEdit(self.save_file_path_line_frame)
        self.save_file_path_line_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.save_file_path_line_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.save_file_path_line_lineEdit.setFont(font)
        self.save_file_path_line_lineEdit.setObjectName("save_file_path_line_lineEdit")
        self.horizontalLayout_12.addWidget(self.save_file_path_line_lineEdit)
        self.save_file_path_line_choose_pushButton = QtWidgets.QPushButton(self.save_file_path_line_frame)
        self.save_file_path_line_choose_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.save_file_path_line_choose_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.save_file_path_line_choose_pushButton.setFont(font)
        self.save_file_path_line_choose_pushButton.setObjectName("save_file_path_line_choose_pushButton")
        self.horizontalLayout_12.addWidget(self.save_file_path_line_choose_pushButton)
        self.verticalLayout_10.addWidget(self.save_file_path_line_frame)
        self.verticalLayout_8.addWidget(self.save_file_path_frame)
        self.document_type_frame = QtWidgets.QFrame(self.export_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.document_type_frame.setFont(font)
        self.document_type_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.document_type_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.document_type_frame.setObjectName("document_type_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.document_type_frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(16)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.report_checkBox = QtWidgets.QCheckBox(self.document_type_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.report_checkBox.setFont(font)
        self.report_checkBox.setChecked(True)
        self.report_checkBox.setObjectName("report_checkBox")
        self.horizontalLayout_14.addWidget(self.report_checkBox)
        self.bid_checkBox = QtWidgets.QCheckBox(self.document_type_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bid_checkBox.setFont(font)
        self.bid_checkBox.setChecked(True)
        self.bid_checkBox.setObjectName("bid_checkBox")
        self.horizontalLayout_14.addWidget(self.bid_checkBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout_8.addWidget(self.document_type_frame)
        self.export_pushButton = QtWidgets.QPushButton(self.export_frame)
        self.export_pushButton.setEnabled(False)
        self.export_pushButton.setMinimumSize(QtCore.QSize(0, 24))
        self.export_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.export_pushButton.setFont(font)
        self.export_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #2563EB;\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B82F6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #DBEAFE;\n"
"    color: #FFFFFF;\n"
"}")
        self.export_pushButton.setObjectName("export_pushButton")
        self.verticalLayout_8.addWidget(self.export_pushButton)
        self.verticalLayout_12.addWidget(self.export_frame)
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem6)
        self.progress_bar_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_frame.sizePolicy().hasHeightForWidth())
        self.progress_bar_frame.setSizePolicy(sizePolicy)
        self.progress_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_bar_frame.setObjectName("progress_bar_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.progress_bar_frame)
        self.verticalLayout_11.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.progress_bar_labels_frame = QtWidgets.QFrame(self.progress_bar_frame)
        self.progress_bar_labels_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_bar_labels_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_bar_labels_frame.setObjectName("progress_bar_labels_frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.progress_bar_labels_frame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.progress_bar_labels_process_label = QtWidgets.QLabel(self.progress_bar_labels_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_labels_process_label.sizePolicy().hasHeightForWidth())
        self.progress_bar_labels_process_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progress_bar_labels_process_label.setFont(font)
        self.progress_bar_labels_process_label.setObjectName("progress_bar_labels_process_label")
        self.horizontalLayout_13.addWidget(self.progress_bar_labels_process_label)
        spacerItem7 = QtWidgets.QSpacerItem(882, 12, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.progress_bar_labels_percents_label = QtWidgets.QLabel(self.progress_bar_labels_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_labels_percents_label.sizePolicy().hasHeightForWidth())
        self.progress_bar_labels_percents_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progress_bar_labels_percents_label.setFont(font)
        self.progress_bar_labels_percents_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progress_bar_labels_percents_label.setObjectName("progress_bar_labels_percents_label")
        self.horizontalLayout_13.addWidget(self.progress_bar_labels_percents_label)
        self.verticalLayout_11.addWidget(self.progress_bar_labels_frame)
        self.progressBar = QtWidgets.QProgressBar(self.progress_bar_frame)
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_11.addWidget(self.progressBar)
        self.verticalLayout_12.addWidget(self.progress_bar_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Создание документа"))
        self.number_label.setText(_translate("MainWindow", "Исх №:"))
        self.number_lineEdit.setPlaceholderText(_translate("MainWindow", "150"))
        self.date_label.setText(_translate("MainWindow", "Дата:"))
        self.ku_label.setText(_translate("MainWindow", "От кого"))
        self.ku_position_label.setText(_translate("MainWindow", "Должность:"))
        self.ku_position_lineEdit.setPlaceholderText(_translate("MainWindow", "Начальник цеха"))
        self.ku_fio_label.setText(_translate("MainWindow", "ФИО:"))
        self.ku_fio_lineEdit.setPlaceholderText(_translate("MainWindow", "Козинец С.М."))
        self.ceh_label.setText(_translate("MainWindow", "Кому"))
        self.ceh_position_label.setText(_translate("MainWindow", "Должность:"))
        self.ceh_position_lineEdit.setPlaceholderText(_translate("MainWindow", "Начальник КУ"))
        self.ceh_fio_label.setText(_translate("MainWindow", "ФИО:"))
        self.ceh_fio_lineEdit.setPlaceholderText(_translate("MainWindow", "Новахович И.В."))
        self.product_label.setText(_translate("MainWindow", "Изделие"))
        self.product_nomenclature_label.setText(_translate("MainWindow", "Номенклатура:"))
        self.product_nomenclature_lineEdit.setPlaceholderText(_translate("MainWindow", "БВВ.02 РИДП.426439.518"))
        self.product_count_label.setText(_translate("MainWindow", "Количество:"))
        self.choose_export_format_label.setText(_translate("MainWindow", "Выберите формат экспорта:"))
        self.export_formats_excel_radioButton.setText(_translate("MainWindow", "Excel (.xlsx)"))
        self.export_formats_word_radioButton.setText(_translate("MainWindow", "Word (.docx)"))
        self.export_formats_pdf_radioButton.setText(_translate("MainWindow", "PDF (.pdf)"))
        self.save_file_path_label.setText(_translate("MainWindow", "Выберите папку для сохранения:"))
        self.save_file_path_line_lineEdit.setPlaceholderText(_translate("MainWindow", "По умолчанию файл сохраняется на рабочий стол"))
        self.save_file_path_line_choose_pushButton.setText(_translate("MainWindow", "Выбрать"))
        self.report_checkBox.setText(_translate("MainWindow", "Докладная"))
        self.bid_checkBox.setText(_translate("MainWindow", "Заявка"))
        self.export_pushButton.setText(_translate("MainWindow", "Экспортировать"))
        self.progress_bar_labels_process_label.setText(_translate("MainWindow", "Процесс..."))
        self.progress_bar_labels_percents_label.setText(_translate("MainWindow", "0%"))
