# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/documentUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 719)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #F2F2F2;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #6B7280;\n"
"    color: #1F2937;\n"
"    font-weight: normal;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #8891A2;\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid #1F2937;\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #E9EFFB;\n"
"    color: #D3DEF5;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #CAD1E0;\n"
"    color: #1F2937;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 1px solid #F5F8FF;\n"
"    color: #D3DEF5;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #CAD1E0;\n"
"    padding: 4px 8px;\n"
"    color: #1F2937;\n"
"    selection-background-color: #2563EB;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QSpinBox:disabled {\n"
"    border: 1px solid #E9EFFB;\n"
"    background-color: #F8FAFC;\n"
"    color: #9CA3AF;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 1px solid #DBEAFE;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #10B981;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QProgressBar[error=\"true\"]::chunk {\n"
"    background-color: #EF4444;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    background-color: #FFFFFF;\n"
"    color: #111827;\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 6px;\n"
"    padding: 4px 8px;\n"
"    min-height: 26px;\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    border-color: #9CA3AF;\n"
"    background-color: #F9FAFB;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border: 2px solid #2563EB;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: right center;\n"
"    width: 26px;\n"
"\n"
"    border-left: 1px solid #D1D5DB;\n"
"    border-top: 1px solid #D1D5DB;\n"
"    border-right: 1px solid #D1D5DB;\n"
"    border-bottom: 1px solid #D1D5DB;\n"
"\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"\n"
"    background-color: #F3F4F6;\n"
"    padding: 0;\n"
"}\n"
"\n"
"QDateEdit::drop-down:hover {\n"
"    background-color: #E5E7EB;\n"
"    border-color: #9CA3AF;\n"
"}\n"
"\n"
"QDateEdit:focus QDateEdit::drop-down {\n"
"    border-color: #2563EB;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    subcontrol-origin: content;\n"
"    subcontrol-position: center;\n"
"    image: url(:/icons/arrow_down.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"}\n"
"\n"
"QDateEdit::drop-down:hover QDateEdit::down-arrow {\n"
"    image: url(:/icons/arrow_down.svg);\n"
"    opacity: 0.8;\n"
"}\n"
"\n"
"QDateEdit:disabled {\n"
"    color: #9CA3AF;\n"
"    background-color: #F3F4F6;\n"
"    border-color: #E5E7EB;\n"
"}\n"
"QDateEdit::drop-down:disabled {\n"
"    background-color: #E5E7EB;\n"
"    border-color: #E5E7EB;\n"
"}\n"
"QDateEdit::down-arrow:disabled {\n"
"    opacity: 0.4;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_12.setSpacing(8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.number_date_frame = QtWidgets.QFrame(self.centralwidget)
        self.number_date_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.number_date_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.number_date_frame.setObjectName("number_date_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.number_date_frame)
        self.horizontalLayout_3.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_3.setSpacing(32)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.number_frame = QtWidgets.QFrame(self.number_date_frame)
        self.number_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.number_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.number_frame.setObjectName("number_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.number_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.number_label = QtWidgets.QLabel(self.number_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_label.sizePolicy().hasHeightForWidth())
        self.number_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.number_label.setFont(font)
        self.number_label.setObjectName("number_label")
        self.horizontalLayout.addWidget(self.number_label)
        self.number_lineEdit = QtWidgets.QLineEdit(self.number_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_lineEdit.sizePolicy().hasHeightForWidth())
        self.number_lineEdit.setSizePolicy(sizePolicy)
        self.number_lineEdit.setMinimumSize(QtCore.QSize(138, 0))
        self.number_lineEdit.setMaximumSize(QtCore.QSize(138, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number_lineEdit.setFont(font)
        self.number_lineEdit.setObjectName("number_lineEdit")
        self.horizontalLayout.addWidget(self.number_lineEdit)
        self.horizontalLayout_3.addWidget(self.number_frame)
        self.date_frame = QtWidgets.QFrame(self.number_date_frame)
        self.date_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_frame.setObjectName("date_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.date_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date_label = QtWidgets.QLabel(self.date_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.horizontalLayout_2.addWidget(self.date_label)
        self.date_dateEdit = QtWidgets.QDateEdit(self.date_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_dateEdit.sizePolicy().hasHeightForWidth())
        self.date_dateEdit.setSizePolicy(sizePolicy)
        self.date_dateEdit.setMinimumSize(QtCore.QSize(138, 36))
        self.date_dateEdit.setMaximumSize(QtCore.QSize(138, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_dateEdit.setFont(font)
        self.date_dateEdit.setStyleSheet("")
        self.date_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_dateEdit.setCalendarPopup(True)
        self.date_dateEdit.setObjectName("date_dateEdit")
        self.horizontalLayout_2.addWidget(self.date_dateEdit)
        self.horizontalLayout_3.addWidget(self.date_frame)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_12.addWidget(self.number_date_frame)
        self.signatures_frame = QtWidgets.QFrame(self.centralwidget)
        self.signatures_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signatures_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signatures_frame.setObjectName("signatures_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.signatures_frame)
        self.horizontalLayout_8.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_8.setSpacing(32)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.from_signature_frame = QtWidgets.QFrame(self.signatures_frame)
        self.from_signature_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.from_signature_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.from_signature_frame.setObjectName("from_signature_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.from_signature_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.from_label = QtWidgets.QLabel(self.from_signature_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_label.sizePolicy().hasHeightForWidth())
        self.from_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.from_label.setFont(font)
        self.from_label.setObjectName("from_label")
        self.verticalLayout_3.addWidget(self.from_label)
        self.from_actions_frame = QtWidgets.QFrame(self.from_signature_frame)
        self.from_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.from_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.from_actions_frame.setObjectName("from_actions_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.from_actions_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.from_position_frame = QtWidgets.QFrame(self.from_actions_frame)
        self.from_position_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.from_position_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.from_position_frame.setObjectName("from_position_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.from_position_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.from_position_label = QtWidgets.QLabel(self.from_position_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.from_position_label.setFont(font)
        self.from_position_label.setObjectName("from_position_label")
        self.horizontalLayout_4.addWidget(self.from_position_label)
        self.from_position_lineEdit = QtWidgets.QLineEdit(self.from_position_frame)
        self.from_position_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.from_position_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.from_position_lineEdit.setFont(font)
        self.from_position_lineEdit.setText("")
        self.from_position_lineEdit.setObjectName("from_position_lineEdit")
        self.horizontalLayout_4.addWidget(self.from_position_lineEdit)
        self.verticalLayout_2.addWidget(self.from_position_frame)
        self.from_fio_frame = QtWidgets.QFrame(self.from_actions_frame)
        self.from_fio_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.from_fio_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.from_fio_frame.setObjectName("from_fio_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.from_fio_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.from_fio_label = QtWidgets.QLabel(self.from_fio_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.from_fio_label.setFont(font)
        self.from_fio_label.setObjectName("from_fio_label")
        self.horizontalLayout_5.addWidget(self.from_fio_label)
        self.from_fio_lineEdit = QtWidgets.QLineEdit(self.from_fio_frame)
        self.from_fio_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.from_fio_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.from_fio_lineEdit.setFont(font)
        self.from_fio_lineEdit.setText("")
        self.from_fio_lineEdit.setObjectName("from_fio_lineEdit")
        self.horizontalLayout_5.addWidget(self.from_fio_lineEdit)
        self.verticalLayout_2.addWidget(self.from_fio_frame)
        self.verticalLayout_3.addWidget(self.from_actions_frame)
        self.horizontalLayout_8.addWidget(self.from_signature_frame)
        self.whom_signature_frame = QtWidgets.QFrame(self.signatures_frame)
        self.whom_signature_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whom_signature_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.whom_signature_frame.setObjectName("whom_signature_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.whom_signature_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.whom_label = QtWidgets.QLabel(self.whom_signature_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whom_label.sizePolicy().hasHeightForWidth())
        self.whom_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.whom_label.setFont(font)
        self.whom_label.setObjectName("whom_label")
        self.verticalLayout_4.addWidget(self.whom_label)
        self.whom_actions_frame = QtWidgets.QFrame(self.whom_signature_frame)
        self.whom_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whom_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.whom_actions_frame.setObjectName("whom_actions_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.whom_actions_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.whom_position_frame = QtWidgets.QFrame(self.whom_actions_frame)
        self.whom_position_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whom_position_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.whom_position_frame.setObjectName("whom_position_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.whom_position_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.whom_position_label = QtWidgets.QLabel(self.whom_position_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.whom_position_label.setFont(font)
        self.whom_position_label.setObjectName("whom_position_label")
        self.horizontalLayout_6.addWidget(self.whom_position_label)
        self.whom_position_lineEdit = QtWidgets.QLineEdit(self.whom_position_frame)
        self.whom_position_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.whom_position_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.whom_position_lineEdit.setFont(font)
        self.whom_position_lineEdit.setText("")
        self.whom_position_lineEdit.setObjectName("whom_position_lineEdit")
        self.horizontalLayout_6.addWidget(self.whom_position_lineEdit)
        self.verticalLayout_5.addWidget(self.whom_position_frame)
        self.whom_fio_frame = QtWidgets.QFrame(self.whom_actions_frame)
        self.whom_fio_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.whom_fio_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.whom_fio_frame.setObjectName("whom_fio_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.whom_fio_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.whom_fio_label = QtWidgets.QLabel(self.whom_fio_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.whom_fio_label.setFont(font)
        self.whom_fio_label.setObjectName("whom_fio_label")
        self.horizontalLayout_7.addWidget(self.whom_fio_label)
        self.whom_fio_lineEdit = QtWidgets.QLineEdit(self.whom_fio_frame)
        self.whom_fio_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.whom_fio_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.whom_fio_lineEdit.setFont(font)
        self.whom_fio_lineEdit.setText("")
        self.whom_fio_lineEdit.setObjectName("whom_fio_lineEdit")
        self.horizontalLayout_7.addWidget(self.whom_fio_lineEdit)
        self.verticalLayout_5.addWidget(self.whom_fio_frame)
        self.verticalLayout_4.addWidget(self.whom_actions_frame)
        self.horizontalLayout_8.addWidget(self.whom_signature_frame)
        self.verticalLayout_12.addWidget(self.signatures_frame)
        self.product_frame = QtWidgets.QFrame(self.centralwidget)
        self.product_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product_frame.setObjectName("product_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.product_frame)
        self.verticalLayout_7.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_7.setSpacing(16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.product_label = QtWidgets.QLabel(self.product_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.product_label.setFont(font)
        self.product_label.setObjectName("product_label")
        self.verticalLayout_7.addWidget(self.product_label)
        self.product_actions_frame = QtWidgets.QFrame(self.product_frame)
        self.product_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product_actions_frame.setObjectName("product_actions_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.product_actions_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(16)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.product_nomenclature_frame = QtWidgets.QFrame(self.product_actions_frame)
        self.product_nomenclature_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product_nomenclature_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product_nomenclature_frame.setObjectName("product_nomenclature_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.product_nomenclature_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.product_nomenclature_label = QtWidgets.QLabel(self.product_nomenclature_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_nomenclature_label.sizePolicy().hasHeightForWidth())
        self.product_nomenclature_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_nomenclature_label.setFont(font)
        self.product_nomenclature_label.setObjectName("product_nomenclature_label")
        self.horizontalLayout_9.addWidget(self.product_nomenclature_label)
        self.product_nomenclature_lineEdit = QtWidgets.QLineEdit(self.product_nomenclature_frame)
        self.product_nomenclature_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.product_nomenclature_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_nomenclature_lineEdit.setFont(font)
        self.product_nomenclature_lineEdit.setObjectName("product_nomenclature_lineEdit")
        self.horizontalLayout_9.addWidget(self.product_nomenclature_lineEdit)
        self.verticalLayout_6.addWidget(self.product_nomenclature_frame)
        self.product_count_frame = QtWidgets.QFrame(self.product_actions_frame)
        self.product_count_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product_count_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product_count_frame.setObjectName("product_count_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.product_count_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.product_count_label = QtWidgets.QLabel(self.product_count_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_count_label.sizePolicy().hasHeightForWidth())
        self.product_count_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_count_label.setFont(font)
        self.product_count_label.setObjectName("product_count_label")
        self.horizontalLayout_10.addWidget(self.product_count_label)
        self.product_count_spinBox = QtWidgets.QSpinBox(self.product_count_frame)
        self.product_count_spinBox.setMinimumSize(QtCore.QSize(138, 0))
        self.product_count_spinBox.setMaximumSize(QtCore.QSize(138, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_count_spinBox.setFont(font)
        self.product_count_spinBox.setMaximum(10000)
        self.product_count_spinBox.setObjectName("product_count_spinBox")
        self.horizontalLayout_10.addWidget(self.product_count_spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_6.addWidget(self.product_count_frame)
        self.verticalLayout_7.addWidget(self.product_actions_frame)
        self.verticalLayout_12.addWidget(self.product_frame)
        self.export_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_frame.sizePolicy().hasHeightForWidth())
        self.export_frame.setSizePolicy(sizePolicy)
        self.export_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_frame.setObjectName("export_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.export_frame)
        self.verticalLayout_8.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_8.setSpacing(16)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.save_file_path_frame = QtWidgets.QFrame(self.export_frame)
        self.save_file_path_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_file_path_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_file_path_frame.setObjectName("save_file_path_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.save_file_path_frame)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.save_file_path_label = QtWidgets.QLabel(self.save_file_path_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_file_path_label.sizePolicy().hasHeightForWidth())
        self.save_file_path_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_file_path_label.setFont(font)
        self.save_file_path_label.setObjectName("save_file_path_label")
        self.verticalLayout_10.addWidget(self.save_file_path_label)
        self.save_file_path_line_frame = QtWidgets.QFrame(self.save_file_path_frame)
        self.save_file_path_line_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_file_path_line_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_file_path_line_frame.setObjectName("save_file_path_line_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.save_file_path_line_frame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.save_file_path_line_lineEdit = QtWidgets.QLineEdit(self.save_file_path_line_frame)
        self.save_file_path_line_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.save_file_path_line_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.save_file_path_line_lineEdit.setFont(font)
        self.save_file_path_line_lineEdit.setObjectName("save_file_path_line_lineEdit")
        self.horizontalLayout_12.addWidget(self.save_file_path_line_lineEdit)
        self.save_file_path_line_choose_pushButton = QtWidgets.QPushButton(self.save_file_path_line_frame)
        self.save_file_path_line_choose_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.save_file_path_line_choose_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.save_file_path_line_choose_pushButton.setFont(font)
        self.save_file_path_line_choose_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_file_path_line_choose_pushButton.setObjectName("save_file_path_line_choose_pushButton")
        self.horizontalLayout_12.addWidget(self.save_file_path_line_choose_pushButton)
        self.verticalLayout_10.addWidget(self.save_file_path_line_frame)
        self.verticalLayout_8.addWidget(self.save_file_path_frame)
        self.document_type_frame_2 = QtWidgets.QFrame(self.export_frame)
        self.document_type_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.document_type_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.document_type_frame_2.setObjectName("document_type_frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.document_type_frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.document_type_frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.document_type_frame = QtWidgets.QFrame(self.document_type_frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.document_type_frame.setFont(font)
        self.document_type_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.document_type_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.document_type_frame.setObjectName("document_type_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.document_type_frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(16)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.document_radioButton = QtWidgets.QRadioButton(self.document_type_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.document_radioButton.setFont(font)
        self.document_radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.document_radioButton.setObjectName("document_radioButton")
        self.horizontalLayout_14.addWidget(self.document_radioButton)
        self.bid_radioButton = QtWidgets.QRadioButton(self.document_type_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bid_radioButton.setFont(font)
        self.bid_radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bid_radioButton.setObjectName("bid_radioButton")
        self.horizontalLayout_14.addWidget(self.bid_radioButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.document_type_frame)
        self.verticalLayout_8.addWidget(self.document_type_frame_2)
        self.export_pushButton = QtWidgets.QPushButton(self.export_frame)
        self.export_pushButton.setEnabled(False)
        self.export_pushButton.setMinimumSize(QtCore.QSize(0, 24))
        self.export_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.export_pushButton.setFont(font)
        self.export_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.export_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #2563EB;\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B82F6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #DBEAFE;\n"
"    color: #FFFFFF;\n"
"}")
        self.export_pushButton.setObjectName("export_pushButton")
        self.verticalLayout_8.addWidget(self.export_pushButton)
        self.verticalLayout_12.addWidget(self.export_frame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem3)
        self.progress_bar_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_frame.sizePolicy().hasHeightForWidth())
        self.progress_bar_frame.setSizePolicy(sizePolicy)
        self.progress_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_bar_frame.setObjectName("progress_bar_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.progress_bar_frame)
        self.verticalLayout_11.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.progress_bar_labels_frame = QtWidgets.QFrame(self.progress_bar_frame)
        self.progress_bar_labels_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_bar_labels_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_bar_labels_frame.setObjectName("progress_bar_labels_frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.progress_bar_labels_frame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.progress_bar_labels_process_label = QtWidgets.QLabel(self.progress_bar_labels_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_labels_process_label.sizePolicy().hasHeightForWidth())
        self.progress_bar_labels_process_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progress_bar_labels_process_label.setFont(font)
        self.progress_bar_labels_process_label.setObjectName("progress_bar_labels_process_label")
        self.horizontalLayout_13.addWidget(self.progress_bar_labels_process_label)
        spacerItem4 = QtWidgets.QSpacerItem(882, 12, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.progress_bar_labels_percents_label = QtWidgets.QLabel(self.progress_bar_labels_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_labels_percents_label.sizePolicy().hasHeightForWidth())
        self.progress_bar_labels_percents_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progress_bar_labels_percents_label.setFont(font)
        self.progress_bar_labels_percents_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progress_bar_labels_percents_label.setObjectName("progress_bar_labels_percents_label")
        self.horizontalLayout_13.addWidget(self.progress_bar_labels_percents_label)
        self.verticalLayout_11.addWidget(self.progress_bar_labels_frame)
        self.progressBar = QtWidgets.QProgressBar(self.progress_bar_frame)
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_11.addWidget(self.progressBar)
        self.verticalLayout_12.addWidget(self.progress_bar_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Создание документа - Stockwise"))
        self.number_label.setText(_translate("MainWindow", "Исх №:"))
        self.number_lineEdit.setPlaceholderText(_translate("MainWindow", "150"))
        self.date_label.setText(_translate("MainWindow", "Дата:"))
        self.from_label.setText(_translate("MainWindow", "От кого"))
        self.from_position_label.setText(_translate("MainWindow", "Должность:"))
        self.from_position_lineEdit.setPlaceholderText(_translate("MainWindow", "Начальник цеха"))
        self.from_fio_label.setText(_translate("MainWindow", "ФИО:"))
        self.from_fio_lineEdit.setPlaceholderText(_translate("MainWindow", "Петров П.Н."))
        self.whom_label.setText(_translate("MainWindow", "Кому"))
        self.whom_position_label.setText(_translate("MainWindow", "Должность:"))
        self.whom_position_lineEdit.setPlaceholderText(_translate("MainWindow", "Начальник КУ"))
        self.whom_fio_label.setText(_translate("MainWindow", "ФИО:"))
        self.whom_fio_lineEdit.setPlaceholderText(_translate("MainWindow", "Иванов. И.И."))
        self.product_label.setText(_translate("MainWindow", "Изделие"))
        self.product_nomenclature_label.setText(_translate("MainWindow", "Номенклатура:"))
        self.product_nomenclature_lineEdit.setPlaceholderText(_translate("MainWindow", "БВВ.02 РИДП.426439.518"))
        self.product_count_label.setText(_translate("MainWindow", "Количество:"))
        self.save_file_path_label.setText(_translate("MainWindow", "Выберите папку для сохранения:"))
        self.save_file_path_line_lineEdit.setPlaceholderText(_translate("MainWindow", "По умолчанию файл сохраняется на рабочий стол"))
        self.save_file_path_line_choose_pushButton.setText(_translate("MainWindow", "Выбрать"))
        self.label.setText(_translate("MainWindow", "Выберите вид документа:"))
        self.document_radioButton.setText(_translate("MainWindow", "Докладная"))
        self.bid_radioButton.setText(_translate("MainWindow", "Заявка"))
        self.export_pushButton.setText(_translate("MainWindow", "Экспортировать"))
        self.progress_bar_labels_process_label.setText(_translate("MainWindow", "Процесс..."))
        self.progress_bar_labels_percents_label.setText(_translate("MainWindow", "0%"))
