# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 706)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #F2F2F2;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"\n"
"/* PushButton */\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #6B7280;\n"
"    color: #1F2937;\n"
"    font-weight: normal;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #8891A2;\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid #1F2937;\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #E9EFFB;\n"
"    color: #D3DEF5;\n"
"}\n"
"\n"
"\n"
"/* LineEdit */\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #CAD1E0;\n"
"    color: #1F2937;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 1px solid #F5F8FF;\n"
"    color: #D3DEF5;\n"
"}\n"
"\n"
"\n"
"/* SpinBox */\n"
"\n"
"QSpinBox {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #CAD1E0;\n"
"    padding: 4px 8px;\n"
"    color: #1F2937;\n"
"    selection-background-color: #2563EB;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QSpinBox:disabled {\n"
"    border: 1px solid #E9EFFB;\n"
"    background-color: #F8FAFC;\n"
"    color: #9CA3AF;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"/* CheckBox */\n"
"\n"
"QCheckBox{\n"
"    color: #0F172A;\n"
"    font-weight: normal;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border-radius: 3px;\n"
"    border: 1px solid #64748B;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 1px solid #2563EB;\n"
"    background-color: #2563EB;\n"
"    image: url(:/icons/checkbox_check);\n"
"}\n"
"\n"
"QCheckBox::indicator:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    border: 1px solid #F8FAFC;\n"
"    background-color: #FFFFFF;\n"
"    image: none;\n"
"}\n"
"\n"
"QCheckBox:disabled {\n"
"    color: #64748B;\n"
"}\n"
"\n"
"\n"
"/* TableWidget */\n"
"\n"
"QTableView,\n"
"QTableWidget {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #d7dde9;\n"
"    border-radius: 6px;\n"
"    gridline-color: #e1e6f2;\n"
"    selection-background-color: #2563EB;\n"
"    selection-color: #ffffff;\n"
"    alternate-background-color: #fafbff;\n"
"    color: #1f2937;\n"
"}\n"
"\n"
"QTableView::item,\n"
"QTableWidget::item {\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QTableView::item:selected,\n"
"QTableWidget::item:selected {\n"
"    background-color: #2563EB;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QTableView::item:hover:!selected,\n"
"QTableWidget::item:hover:!selected {\n"
"    background-color: #eef2fb;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f6f7fb;\n"
"    color: #374151;\n"
"    padding: 4px 6px;\n"
"    border: none;\n"
"    border-right: 1px solid #e1e6f2;\n"
"    border-bottom: 1px solid #d7dde9;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    background-color: #f2f4fa;\n"
"    color: #4b5563;\n"
"    padding: 2px 4px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f6f7fb;\n"
"    border: none;\n"
"    border-right: 1px solid #d7dde9;\n"
"    border-bottom: 1px solid #d7dde9;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 10px;\n"
"    margin: 2px 0 2px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #d3d9e8;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #c5ccdd;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: 10px;\n"
"    margin: 0 2px 0 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #d3d9e8;\n"
"    min-width: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #c5ccdd;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.search_frame = QtWidgets.QFrame(self.centralwidget)
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_frame.setObjectName("search_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.search_frame)
        self.verticalLayout_2.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_line_frame = QtWidgets.QFrame(self.search_frame)
        self.search_line_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.search_line_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_line_frame.setObjectName("search_line_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.search_line_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_line_label = QtWidgets.QLabel(self.search_line_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.search_line_label.setFont(font)
        self.search_line_label.setObjectName("search_line_label")
        self.horizontalLayout.addWidget(self.search_line_label)
        self.search_line_lineEdit = QtWidgets.QLineEdit(self.search_line_frame)
        self.search_line_lineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_line_lineEdit.sizePolicy().hasHeightForWidth())
        self.search_line_lineEdit.setSizePolicy(sizePolicy)
        self.search_line_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.search_line_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.search_line_lineEdit.setFont(font)
        self.search_line_lineEdit.setClearButtonEnabled(True)
        self.search_line_lineEdit.setObjectName("search_line_lineEdit")
        self.horizontalLayout.addWidget(self.search_line_lineEdit)
        self.search_filters_pushButton = QtWidgets.QPushButton(self.search_line_frame)
        self.search_filters_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_filters_pushButton.sizePolicy().hasHeightForWidth())
        self.search_filters_pushButton.setSizePolicy(sizePolicy)
        self.search_filters_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.search_filters_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.search_filters_pushButton.setFont(font)
        self.search_filters_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/filters/default.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/filters/disabled.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/filters/disabled.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/filters/hover.svg"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/filters/hover.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/filters/clicked.svg"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/filters/clicked.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.search_filters_pushButton.setIcon(icon)
        self.search_filters_pushButton.setIconSize(QtCore.QSize(18, 20))
        self.search_filters_pushButton.setObjectName("search_filters_pushButton")
        self.horizontalLayout.addWidget(self.search_filters_pushButton)
        self.verticalLayout_2.addWidget(self.search_line_frame)
        self.search_in_materials_checkBox = QtWidgets.QCheckBox(self.search_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.search_in_materials_checkBox.setFont(font)
        self.search_in_materials_checkBox.setObjectName("search_in_materials_checkBox")
        self.verticalLayout_2.addWidget(self.search_in_materials_checkBox)
        self.verticalLayout_6.addWidget(self.search_frame)
        self.norms_calculations_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norms_calculations_frame.sizePolicy().hasHeightForWidth())
        self.norms_calculations_frame.setSizePolicy(sizePolicy)
        self.norms_calculations_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.norms_calculations_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.norms_calculations_frame.setObjectName("norms_calculations_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.norms_calculations_frame)
        self.horizontalLayout_2.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.norms_calculations_lalabel = QtWidgets.QLabel(self.norms_calculations_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norms_calculations_lalabel.sizePolicy().hasHeightForWidth())
        self.norms_calculations_lalabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.norms_calculations_lalabel.setFont(font)
        self.norms_calculations_lalabel.setObjectName("norms_calculations_lalabel")
        self.horizontalLayout_2.addWidget(self.norms_calculations_lalabel)
        self.norms_calculations_spinBox = QtWidgets.QSpinBox(self.norms_calculations_frame)
        self.norms_calculations_spinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.norms_calculations_spinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.norms_calculations_spinBox.setFont(font)
        self.norms_calculations_spinBox.setMaximum(999999)
        self.norms_calculations_spinBox.setProperty("value", 1)
        self.norms_calculations_spinBox.setObjectName("norms_calculations_spinBox")
        self.horizontalLayout_2.addWidget(self.norms_calculations_spinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.norms_calculations_frame)
        self.table_frame = QtWidgets.QFrame(self.centralwidget)
        self.table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_frame.setObjectName("table_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.table_frame)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.data_tableWidget = QtWidgets.QTableWidget(self.table_frame)
        self.data_tableWidget.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.data_tableWidget.setFont(font)
        self.data_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.data_tableWidget.setAlternatingRowColors(True)
        self.data_tableWidget.setObjectName("data_tableWidget")
        self.data_tableWidget.setColumnCount(0)
        self.data_tableWidget.setRowCount(0)
        self.data_tableWidget.horizontalHeader().setStretchLastSection(False)
        self.data_tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.data_tableWidget)
        self.verticalLayout_6.addWidget(self.table_frame)
        self.create_document_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_document_frame.sizePolicy().hasHeightForWidth())
        self.create_document_frame.setSizePolicy(sizePolicy)
        self.create_document_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.create_document_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_document_frame.setObjectName("create_document_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.create_document_frame)
        self.verticalLayout_5.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_5.setSpacing(16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.export_pushButton = QtWidgets.QPushButton(self.create_document_frame)
        self.export_pushButton.setEnabled(False)
        self.export_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.export_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.export_pushButton.setFont(font)
        self.export_pushButton.setObjectName("export_pushButton")
        self.verticalLayout_5.addWidget(self.export_pushButton)
        self.create_document_pushButton = QtWidgets.QPushButton(self.create_document_frame)
        self.create_document_pushButton.setEnabled(False)
        self.create_document_pushButton.setMinimumSize(QtCore.QSize(0, 24))
        self.create_document_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.create_document_pushButton.setFont(font)
        self.create_document_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #2563EB;\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B82F6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #DBEAFE;\n"
"    color: #FFFFFF;\n"
"}")
        self.create_document_pushButton.setObjectName("create_document_pushButton")
        self.verticalLayout_5.addWidget(self.create_document_pushButton)
        self.verticalLayout_6.addWidget(self.create_document_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stockwise"))
        self.search_line_label.setText(_translate("MainWindow", "Поиск:"))
        self.search_line_lineEdit.setPlaceholderText(_translate("MainWindow", "Поиск по названию..."))
        self.search_in_materials_checkBox.setText(_translate("MainWindow", "Поиск по материалам изделия"))
        self.norms_calculations_lalabel.setText(_translate("MainWindow", "Нормы на количество:"))
        self.export_pushButton.setText(_translate("MainWindow", "Экспортировать"))
        self.create_document_pushButton.setText(_translate("MainWindow", "Создать документ"))
import resources.resources_rc
