# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #F2F2F2;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #6B7280;\n"
"    color: #1F2937;\n"
"    font-weight: normal;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #8891A2;\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid #1F2937;\n"
"    color: #1F2937;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #E9EFFB;\n"
"    color: #D3DEF5;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #CAD1E0;\n"
"    color: #1F2937;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 1px solid #F5F8FF;\n"
"    color: #D3DEF5;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #CAD1E0;\n"
"    padding: 4px 8px;\n"
"    color: #1F2937;\n"
"    selection-background-color: #2563EB;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"QSpinBox:disabled {\n"
"    border: 1px solid #E9EFFB;\n"
"    background-color: #F8FAFC;\n"
"    color: #9CA3AF;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 1px solid #DBEAFE;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #10B981;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QProgressBar[error=\"true\"]::chunk {\n"
"    background-color: #EF4444;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #1F2937;\n"
"    spacing: 4px;\n"
"    border-radius: 6px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.search_frame = QtWidgets.QFrame(self.centralwidget)
        self.search_frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_frame.sizePolicy().hasHeightForWidth())
        self.search_frame.setSizePolicy(sizePolicy)
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_frame.setObjectName("search_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.search_frame)
        self.verticalLayout.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_line_frame = QtWidgets.QFrame(self.search_frame)
        self.search_line_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.search_line_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_line_frame.setObjectName("search_line_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.search_line_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_line_label = QtWidgets.QLabel(self.search_line_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.search_line_label.setFont(font)
        self.search_line_label.setObjectName("search_line_label")
        self.horizontalLayout.addWidget(self.search_line_label)
        self.search_line_lineEdit = QtWidgets.QLineEdit(self.search_line_frame)
        self.search_line_lineEdit.setEnabled(True)
        self.search_line_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.search_line_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.search_line_lineEdit.setFont(font)
        self.search_line_lineEdit.setObjectName("search_line_lineEdit")
        self.horizontalLayout.addWidget(self.search_line_lineEdit)
        self.search_line_clear_pushButton = QtWidgets.QPushButton(self.search_line_frame)
        self.search_line_clear_pushButton.setEnabled(False)
        self.search_line_clear_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.search_line_clear_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.search_line_clear_pushButton.setFont(font)
        self.search_line_clear_pushButton.setObjectName("search_line_clear_pushButton")
        self.horizontalLayout.addWidget(self.search_line_clear_pushButton)
        self.verticalLayout.addWidget(self.search_line_frame)
        self.search_checkBox = QtWidgets.QCheckBox(self.search_frame)
        self.search_checkBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_checkBox.sizePolicy().hasHeightForWidth())
        self.search_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.search_checkBox.setFont(font)
        self.search_checkBox.setChecked(False)
        self.search_checkBox.setObjectName("search_checkBox")
        self.verticalLayout.addWidget(self.search_checkBox)
        self.verticalLayout_6.addWidget(self.search_frame)
        self.norms_calculations_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norms_calculations_frame.sizePolicy().hasHeightForWidth())
        self.norms_calculations_frame.setSizePolicy(sizePolicy)
        self.norms_calculations_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.norms_calculations_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.norms_calculations_frame.setObjectName("norms_calculations_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.norms_calculations_frame)
        self.horizontalLayout_2.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.norms_calculations_lalabel = QtWidgets.QLabel(self.norms_calculations_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norms_calculations_lalabel.sizePolicy().hasHeightForWidth())
        self.norms_calculations_lalabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.norms_calculations_lalabel.setFont(font)
        self.norms_calculations_lalabel.setObjectName("norms_calculations_lalabel")
        self.horizontalLayout_2.addWidget(self.norms_calculations_lalabel)
        self.norms_calculations_spinBox = QtWidgets.QSpinBox(self.norms_calculations_frame)
        self.norms_calculations_spinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.norms_calculations_spinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.norms_calculations_spinBox.setFont(font)
        self.norms_calculations_spinBox.setMaximum(999999)
        self.norms_calculations_spinBox.setProperty("value", 100)
        self.norms_calculations_spinBox.setObjectName("norms_calculations_spinBox")
        self.horizontalLayout_2.addWidget(self.norms_calculations_spinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.norms_calculations_frame)
        self.data_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.data_tableWidget.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.data_tableWidget.setFont(font)
        self.data_tableWidget.setObjectName("data_tableWidget")
        self.data_tableWidget.setColumnCount(0)
        self.data_tableWidget.setRowCount(0)
        self.data_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.data_tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.data_tableWidget)
        self.export_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_frame.sizePolicy().hasHeightForWidth())
        self.export_frame.setSizePolicy(sizePolicy)
        self.export_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_frame.setObjectName("export_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.export_frame)
        self.verticalLayout_4.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.choose_export_format_frame = QtWidgets.QFrame(self.export_frame)
        self.choose_export_format_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_export_format_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_export_format_frame.setObjectName("choose_export_format_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.choose_export_format_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.choose_export_format_label = QtWidgets.QLabel(self.choose_export_format_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_export_format_label.sizePolicy().hasHeightForWidth())
        self.choose_export_format_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_export_format_label.setFont(font)
        self.choose_export_format_label.setObjectName("choose_export_format_label")
        self.verticalLayout_2.addWidget(self.choose_export_format_label)
        self.export_formats_frame = QtWidgets.QFrame(self.choose_export_format_frame)
        self.export_formats_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_formats_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_formats_frame.setObjectName("export_formats_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.export_formats_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(16)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.export_formats_excel_radioButton = QtWidgets.QRadioButton(self.export_formats_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export_formats_excel_radioButton.setFont(font)
        self.export_formats_excel_radioButton.setChecked(True)
        self.export_formats_excel_radioButton.setObjectName("export_formats_excel_radioButton")
        self.horizontalLayout_3.addWidget(self.export_formats_excel_radioButton)
        self.export_formats_word_radioButton = QtWidgets.QRadioButton(self.export_formats_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export_formats_word_radioButton.setFont(font)
        self.export_formats_word_radioButton.setObjectName("export_formats_word_radioButton")
        self.horizontalLayout_3.addWidget(self.export_formats_word_radioButton)
        self.export_formats_pdf_radioButton = QtWidgets.QRadioButton(self.export_formats_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export_formats_pdf_radioButton.setFont(font)
        self.export_formats_pdf_radioButton.setObjectName("export_formats_pdf_radioButton")
        self.horizontalLayout_3.addWidget(self.export_formats_pdf_radioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.export_formats_frame)
        self.verticalLayout_4.addWidget(self.choose_export_format_frame)
        self.save_file_path_frame = QtWidgets.QFrame(self.export_frame)
        self.save_file_path_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_file_path_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_file_path_frame.setObjectName("save_file_path_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.save_file_path_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.save_file_path_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.save_file_path_line_frame = QtWidgets.QFrame(self.save_file_path_frame)
        self.save_file_path_line_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_file_path_line_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_file_path_line_frame.setObjectName("save_file_path_line_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.save_file_path_line_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.save_file_path_line_lineEdit = QtWidgets.QLineEdit(self.save_file_path_line_frame)
        self.save_file_path_line_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.save_file_path_line_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.save_file_path_line_lineEdit.setFont(font)
        self.save_file_path_line_lineEdit.setObjectName("save_file_path_line_lineEdit")
        self.horizontalLayout_4.addWidget(self.save_file_path_line_lineEdit)
        self.save_file_path_line_choose_pushButton = QtWidgets.QPushButton(self.save_file_path_line_frame)
        self.save_file_path_line_choose_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.save_file_path_line_choose_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.save_file_path_line_choose_pushButton.setFont(font)
        self.save_file_path_line_choose_pushButton.setObjectName("save_file_path_line_choose_pushButton")
        self.horizontalLayout_4.addWidget(self.save_file_path_line_choose_pushButton)
        self.verticalLayout_3.addWidget(self.save_file_path_line_frame)
        self.verticalLayout_4.addWidget(self.save_file_path_frame)
        self.export_pushButton = QtWidgets.QPushButton(self.export_frame)
        self.export_pushButton.setEnabled(False)
        self.export_pushButton.setMinimumSize(QtCore.QSize(0, 24))
        self.export_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.export_pushButton.setFont(font)
        self.export_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #2563EB;\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B82F6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #DBEAFE;\n"
"    color: #FFFFFF;\n"
"}")
        self.export_pushButton.setObjectName("export_pushButton")
        self.verticalLayout_4.addWidget(self.export_pushButton)
        self.verticalLayout_6.addWidget(self.export_frame)
        self.progress_bar_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_frame.sizePolicy().hasHeightForWidth())
        self.progress_bar_frame.setSizePolicy(sizePolicy)
        self.progress_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_bar_frame.setObjectName("progress_bar_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.progress_bar_frame)
        self.verticalLayout_5.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.progress_bar_labels_frame = QtWidgets.QFrame(self.progress_bar_frame)
        self.progress_bar_labels_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_bar_labels_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_bar_labels_frame.setObjectName("progress_bar_labels_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.progress_bar_labels_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progress_bar_labels_process_label = QtWidgets.QLabel(self.progress_bar_labels_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_labels_process_label.sizePolicy().hasHeightForWidth())
        self.progress_bar_labels_process_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progress_bar_labels_process_label.setFont(font)
        self.progress_bar_labels_process_label.setObjectName("progress_bar_labels_process_label")
        self.horizontalLayout_5.addWidget(self.progress_bar_labels_process_label)
        spacerItem2 = QtWidgets.QSpacerItem(882, 12, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.progress_bar_labels_percents_label = QtWidgets.QLabel(self.progress_bar_labels_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_labels_percents_label.sizePolicy().hasHeightForWidth())
        self.progress_bar_labels_percents_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progress_bar_labels_percents_label.setFont(font)
        self.progress_bar_labels_percents_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progress_bar_labels_percents_label.setObjectName("progress_bar_labels_percents_label")
        self.horizontalLayout_5.addWidget(self.progress_bar_labels_percents_label)
        self.verticalLayout_5.addWidget(self.progress_bar_labels_frame)
        self.progressBar = QtWidgets.QProgressBar(self.progress_bar_frame)
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_5.addWidget(self.progressBar)
        self.verticalLayout_6.addWidget(self.progress_bar_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stockwise"))
        self.search_line_label.setText(_translate("MainWindow", "Поиск:"))
        self.search_line_lineEdit.setPlaceholderText(_translate("MainWindow", "БВВ.01"))
        self.search_line_clear_pushButton.setText(_translate("MainWindow", "Очистить"))
        self.search_checkBox.setText(_translate("MainWindow", "Поиск по материалам"))
        self.norms_calculations_lalabel.setText(_translate("MainWindow", "Нормы на количество:"))
        self.choose_export_format_label.setText(_translate("MainWindow", "Выберите формат экспорта:"))
        self.export_formats_excel_radioButton.setText(_translate("MainWindow", "Excel (.xlsx)"))
        self.export_formats_word_radioButton.setText(_translate("MainWindow", "Word (.docx)"))
        self.export_formats_pdf_radioButton.setText(_translate("MainWindow", "PDF (.pdf)"))
        self.label.setText(_translate("MainWindow", "Выберите папку для сохранения:"))
        self.save_file_path_line_lineEdit.setPlaceholderText(_translate("MainWindow", "По умолчанию файл сохраняется на рабочий стол"))
        self.save_file_path_line_choose_pushButton.setText(_translate("MainWindow", "Выбрать"))
        self.export_pushButton.setText(_translate("MainWindow", "Экспортировать"))
        self.progress_bar_labels_process_label.setText(_translate("MainWindow", "Процесс..."))
        self.progress_bar_labels_percents_label.setText(_translate("MainWindow", "0%"))
